import { ArrowUpRight, Cpu, HardDrive, MemoryStick, Network, ShieldCheck, Plus } from 'lucide-react';
import { products, upgradeNote } from '@/lib/products';
import { Family, Exterior, Services } from '@/components/crumbwaffle/shared';
import { FAQ, Waitlist } from '@/components/crumbwaffle/interactive';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell, TableCaption } from '@/components/ui/table';
const rows = [ ['Processor', (p:typeof products[number])=>p.cpu], ['DDR5 memory', (p:typeof products[number])=>`${p.ram} · replaceable`], ['Storage', (p:typeof products[number])=>p.storage], ['Graphics at purchase', (p:typeof products[number])=>`${p.gpu} · ${p.vram}`], ['Made for', (p:typeof products[number])=>p.audience], ['Upgrade path', (p:typeof products[number])=>`DDR5 + removable SSD + ${p.bay.toLowerCase()}`] ] as const;
export default function Home() { return <main id="main">
 <section className="hero wrap"><div className="hero-heading"><p className="eyebrow"><span className="status-dot"/>LOCAL INTELLIGENCE. PERSONAL PROPERTY.</p><h1>Your own AI.<br/>In a box called <span>CrumbWaffle.</span></h1><p className="hero-sub">A private AI assistant and local server<br className="desktop"/> you can keep, control, and upgrade.</p><div className="actions"><a className="action" href="#boxes">Explore the boxes. <ArrowUpRight size={17}/></a><a className="action secondary" href="#inside">How it works. <span>↓</span></a></div><p className="dry-line">Yes, that’s really the name.</p></div><Family/><div className="hero-foot"><span>DESIGNED TO STAY YOURS.</span><span>FOUR MODELS. ONE LESS REASON TO RENT YOUR INTELLIGENCE.</span><span>CONCEPT SERIES / 01</span></div></section>
 <section className="intro-video wrap" aria-labelledby="intro-video-title"><div className="intro-video-copy"><p className="eyebrow">THE IDEA / 30 SECONDS</p><h2 id="intro-video-title">Meet CrumbWaffle.</h2><p>A quick look at the concept behind your own AI in a box.</p></div><div className="intro-video-player"><video controls playsInline preload="none" poster="/video/crumbwaffle-intro-poster.jpg" aria-label="CrumbWaffle company introduction video"><source src="/video/crumbwaffle-intro.mp4" type="video/mp4"/>Your browser does not support this video.</video></div></section>
 <div className="concept-bar"><span className="status-dot"/>Meet a work in progress. All specifications, prices, and capabilities are proposed concepts.</div>
 <section className="section wrap inside" id="inside" data-reveal><div className="section-head"><div><p className="eyebrow">01 / UNDER THE LID</p><h2>What’s inside?<br/><span>Glad you asked.</span></h2></div><p>A local mind. A private server.<br/>Parts that aren’t a permanent decision.</p></div><div className="inside-grid"><div className="technical-plate"><div className="plate-label"><span>HOME / EXPLODED VIEW</span><Plus size={18}/></div><img src="/products/home-cutaway.png" alt="Home technical concept showing motherboard, removable memory, SSD, cooling, and empty GPU bay" loading="lazy"/><span className="plate-caption">COMPONENT STUDY · PROPOSED CONFIGURATION</span></div><div className="inside-list">{[[Cpu,'A local AI model','A planned assistant running on your own hardware, for supported everyday tasks.'],[Network,'Your private server','A place for files, routines, and local services on your own network.'],[MemoryStick,'Memory with a future','Replaceable DDR5. Start with what you need; expand within validated limits.'],[HardDrive,'Storage you can remove','Your SSD is a component, not a lifetime commitment.'],[ShieldCheck,'Room to change your mind','An upgrade path for compatible hardware. Keep the box useful for longer.']].map(([Icon,title,copy],i)=>{const I=Icon as typeof Cpu; return <article key={i}><span className="component-number">0{i+1}</span><I size={24} strokeWidth={1.3}/><div><h3>{title as string}</h3><p>{copy as string}</p></div></article>})}</div></div><div className="flow" aria-label="How local AI works"><span>Your device</span><i/><span>Your local network</span><i/><span>CrumbWaffle</span><i/><span>Your files & model</span></div><p className="fineprint">Local by design. Setup, downloads, updates, and any chosen external services may need internet access.</p></section>
 <section className="section wrap boxes" id="boxes" data-reveal><div className="section-head"><div><p className="eyebrow">02 / MEET THE FAMILY</p><h2>Find your kind of box.</h2></div><p>From a few home routines<br/>to a room full of good questions.</p></div><div className="product-grid">{products.map(p=><article className="product-card" key={p.slug}><div className="card-top"><span className="eyebrow">CW / 0{p.index+1}</span>{p.slug==='home'&&<span className="pill">SMALLEST FOOTPRINT</span>}</div><a href={`/models/${p.slug}`} aria-label={`Explore ${p.name}`}><Exterior product={p}/></a><div className="product-title"><h3>{p.name}</h3><span>{p.price}</span></div><p className="product-audience">{p.audience}</p><ul><li>{p.cpu.replace('AMD ','')}</li><li>{p.ram} DDR5 · {p.storage}</li><li>{p.gpu.replace('NVIDIA ','')}{p.index>1?` · ${p.vram}`:''}</li><li>{p.index<2?'Empty PCIe GPU bay':'Replaceable graphics card'}</li></ul><a className="model-link" href={`/models/${p.slug}`}>Explore model <ArrowUpRight size={18}/></a></article>)}</div><p className="fineprint">Proposed USD prices. Includes the listed configuration, planned software, one-year hardware warranty, and basic support. Not available to order.</p></section>
 <section className="section wrap comparison" id="compare" data-reveal><div className="section-head"><div><p className="eyebrow">03 / THE PARTICULARS</p><h2>Same philosophy.<br/>Different amounts of box.</h2></div><p className="mobile-scroll">Swipe the table to compare all four models →</p></div><div className="comparison-scroll" tabIndex={0} role="region" aria-label="Model comparison, scroll horizontally"><Table><TableCaption>Proposed configurations. All GPU changes require space, power, cooling, and CrumbWaffle validation.</TableCaption><TableHeader><TableRow><TableHead scope="col">The details</TableHead>{products.map(p=><TableHead scope="col" key={p.slug}><a href={`/models/${p.slug}`}>{p.name} ↗</a><span>{p.price}</span></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(([label,get])=><TableRow key={label}><TableHead scope="row">{label}</TableHead>{products.map(p=><TableCell key={p.slug}>{get(p)}</TableCell>)}</TableRow>)}</TableBody></Table></div></section>
 <section className="section wrap stories" id="everyday" data-reveal><div className="section-head"><div><p className="eyebrow">04 / LESS ABSTRACT. MORE EVERYDAY.</p><h2>AI that has a place.</h2></div><p>These are illustrative workflows,<br/>not announced integrations.</p></div><div className="stories-grid">{[{title:'At the front door',copy:'A supported arrival routine brings your home into the evening. Local controls, with compatible devices you choose.',screen:'Evening routine',items:['Entry lighting · scheduled','Hallway · ready','Local network · connected'],foot:'ILLUSTRATIVE HOME ROUTINE'}, {title:'At your desk',copy:'Find the paragraph you remember, in the document you don’t. Search your own files with a planned local assistant.',screen:'Where is the project brief?',items:['Project brief.pdf · page 2','Found in your local library','Answer with source references'],foot:'ILLUSTRATIVE DOCUMENT SEARCH'}, {title:'Across the team',copy:'Give company knowledge a home inside the company. A shared collection of documents, with access you manage.',screen:'Team knowledge',items:['Operations handbook','Client project notes','Access · authorized team'],foot:'ILLUSTRATIVE TEAM WORKSPACE'}].map((s,i)=><article key={s.title}><div className={`space-image space-${i}`} role="img" aria-label={['Bright home entry with a compact AI box','Bright desk with a personal AI server','Bright small business workspace'][i]}/><div className="ui-demo"><div className="ui-top"><span className="status-dot"/> CRUMBWAFFLE / LOCAL</div><strong>{s.screen}</strong>{s.items.map(t=><p key={t}><span>↳</span>{t}</p>)}<span className="ui-foot">{s.foot}</span></div><h3>{s.title}</h3><p>{s.copy}</p></article>)}</div></section>
 <section className="section wrap upgrade" id="upgrade" data-reveal><div className="upgrade-copy"><p className="eyebrow">05 / OWNERSHIP, WITH SCREWS</p><h2>Open it.<br/>Upgrade it.<br/><span>Keep it.</span></h2><p>More memory. New storage. A compatible graphics card. Your next chapter shouldn’t always require a new computer.</p><p className="dry-line">Planned obsolescence was not invited.</p><a className="text-link" href="/models/standard#upgrades">Explore the upgrade path <ArrowUpRight size={16}/></a></div><figure className="upgrade-figure"><img src="/images/upgrade.png" alt="Standard tower concept with the side panel removed and graphics card shown outside its slot" loading="lazy"/><figcaption>STANDARD / SERVICEABILITY STUDY · CONCEPT ILLUSTRATION</figcaption></figure><div className="upgrade-note"><ShieldCheck size={23}/><p>{upgradeNote}</p></div></section>
 <Services/>
 <section className="section wrap faq-section" id="faq" data-reveal><div><p className="eyebrow">07 / REASONABLE QUESTIONS</p><h2>A few things<br/>before the box.</h2><p>The name is settled.<br/>Some details are still in development.</p></div><FAQ/></section>
 <section id="waitlist" className="section wrap final-section" data-reveal><p className="eyebrow">YOUR NEXT COMPUTER COULD BE YOUR OWN AI.</p><h2>Keep your intelligence close.</h2><Family small/><div className="waitlist-grid"><div><h3>Join the waitlist.</h3><p>For now, take a look around.<br/>We’re still putting the box together.</p></div><Waitlist/></div></section>
 </main> }
