export const products = [
  { slug: 'private', name: 'Private', price: '$649', cpu: 'AMD Ryzen 5 8600G', ram: '16 GB', storage: '256 GB SSD', gpu: 'Integrated graphics', vram: 'Shared system memory', bay: 'Empty PCIe GPU bay', audience: 'Basic home setup & automations', line: 'A little independence.', description: 'A personal starting point for a local server and simple home routines. Your first box. Very much your box.', capabilities: ['Basic home routines with compatible devices', 'Personal files on your own local server', 'Entry-level local AI experiments'], index: 0 },
  { slug: 'home', name: 'Home', price: '$1,099', cpu: 'AMD Ryzen 5 8600G', ram: '32 GB', storage: '512 GB SSD', gpu: 'Integrated graphics', vram: 'Shared system memory', bay: 'Empty PCIe GPU bay', audience: 'Households & more connected devices', line: 'Small box. House duties.', description: 'Our smallest enclosure, with more memory and storage than Private. A local household assistant and a home for your everyday routines.', capabilities: ['A local household assistant', 'More room for routines and compatible devices', 'Shared household files and local services'], index: 1 },
  { slug: 'standard', name: 'Standard', price: '$1,999', cpu: 'AMD Ryzen 5 7600', ram: '32 GB', storage: '1 TB NVMe SSD', gpu: 'NVIDIA RTX 5060 Ti', vram: '16 GB VRAM', bay: 'Replaceable PCIe graphics card', audience: 'Individuals & private work', line: 'Bring your work home. Locally.', description: 'Dedicated graphics for a private work assistant, document search, and a local server. For files that have no business leaving your business.', capabilities: ['Search a local collection of your documents', 'A private work assistant with dedicated graphics', 'Local file storage and personal server workloads'], index: 2 },
  { slug: 'enterprise', name: 'Enterprise', price: '$4,499', cpu: 'AMD Ryzen 9 9900X', ram: '64 GB', storage: '1 TB NVMe SSD', gpu: 'NVIDIA RTX PRO 4000 Blackwell', vram: '24 GB VRAM', bay: 'Replaceable PCIe graphics card', audience: 'Small businesses & teams', line: 'Company knowledge. Company property.', description: 'A proposed foundation for shared private AI and business knowledge. A serious workstation for a small team. The name has already been approved.', capabilities: ['Shared business knowledge on a local server', 'Team document search with planned access controls', 'Dedicated workstation graphics for local AI'], index: 3 },
] as const;
export type Product = typeof products[number];
export const upgradeNote = 'Compatible cards depend on available space, power, cooling, and CrumbWaffle validation. An empty bay is an upgrade path, not a promise that every GPU will fit.';
export const faqs = [
 ['Does the AI run locally or in the cloud?', 'The concept is built around a local AI model and local server. Core supported tasks are intended to run on the box. Any future cloud features would need to be separately disclosed and enabled; none are promised here.'],
 ['Will I need an internet connection?', 'Plan on internet access for initial setup, model downloads, updates, and any external services you choose. Supported local tasks are intended to work over your home or office network after setup. Offline capabilities are still being defined.'],
 ['How private is private?', 'The design goal is local processing and storage for supported tasks. Privacy also depends on device access, network security, configuration, and any external service you enable. This is a proposed design, not a completed security audit or a claim of perfect privacy.'],
 ['Which home devices will it work with?', 'The compatibility list has not been finalized. Device support will depend on local protocols and validated integrations. No smart-home brand or platform integration is promised on this concept site.'],
 ['Can I add or replace the GPU?', upgradeNote + ' Private and Home are proposed with integrated graphics and an empty PCIe bay. Standard and Enterprise include the listed replaceable dedicated card.'],
 ['What does the proposed price include?', 'The listed hardware configuration, a planned local AI and server software setup, a one-year hardware warranty, and basic support. Setup assistance, priority support, and an extended hardware warranty would be optional paid services. Tax, delivery, service pricing, model selection, and final terms are not yet set.'],
 ['Can I order one now?', 'Not yet. CrumbWaffle is a fictional product concept. Prices, specifications, imagery, and capabilities are proposed and may change. This site has no checkout, shipping commitment, or live waitlist.'],
] as const;
